version: "3.0"
services:
  asterisk:
    build: ./asterisk
    container_name: asterisk
    depends_on:
      - db
    network_mode: host
    volumes:
      - ./asterisk/config:/etc/asterisk
  db:
    container_name: mariadb
    image: mariadb
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  nginx:
    container_name: nginx
    image: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build/phone:/usr/share/nginx/html
  coturn:
    container_name: coturn
    image: instrumentisto/coturn
    network_mode: host
    restart: always
