version: "3.0"
services:
  asterisk:
    build: ./asterisk
    container_name: asterisk
    depends_on:
      - db
    network_mode: host
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/config.ini:/root/asterisk/contrib/ast-db-manage/config.ini
      - ./asterisk/odbcinst.ini:/etc/odbcinst.ini
      - ./asterisk/odbc.ini:/etc/odbc.ini
  db:
    container_name: postgres
    environment:
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: ca11ftw
    image: postgres:latest
    network_mode: host
    restart: always
    volumes:
      - ./postgres/database_data:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build:/usr/share/nginx/html
  coturn:
    container_name: coturn
    image: instrumentisto/coturn
    network_mode: host
    restart: always
